#!/data/data/com.termux/files/usr/bin/bash
# Install Termux home-screen shortcuts and boot script
set -euo pipefail

HOME_DIR="$HOME"
SHORTCUT_DIR="$HOME_DIR/.shortcuts"
BOOT_DIR="$HOME_DIR/.termux/boot"

echo "[*] Installing home-screen shortcuts..."
mkdir -p "$SHORTCUT_DIR" "$BOOT_DIR"

# 1. LaunchAll
cat > "$SHORTCUT_DIR/LaunchAll" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
banner() {
    echo "========================================"
    echo "$1"
    echo "========================================"
    echo ""
}
wait_key() {
    echo ""
    read -n 1 -s -r -p "Tap any key to close..." || true
    echo ""
}
notify() {
    termux-toast "$1" 2>/dev/null || true
}

banner "LaunchAll - Starting all scanners"
export ALCHEMY_API_KEY="${ALCHEMY_API_KEY:-mi8wM6xm7rRBMYTCjHfM5}"
notify "Launching all scanners..."
bash "$HOME/launch_all.sh"
echo ""
echo "Recent log output:"
tail -n 30 "$HOME/launch_all.log" 2>/dev/null || echo "[no log yet]"
echo ""
echo "Services are running in the background."
wait_key
EOF

# 2. CryptoScanner (wallet scanner button)
cat > "$SHORTCUT_DIR/CryptoScanner" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
banner() {
    echo "========================================"
    echo "$1"
    echo "========================================"
    echo ""
}
wait_key() {
    echo ""
    read -n 1 -s -r -p "Tap any key to close..." || true
    echo ""
}
notify() {
    termux-toast "$1" 2>/dev/null || true
}

banner "CryptoScanner - Wallet Scanner"
export ALCHEMY_API_KEY="${ALCHEMY_API_KEY:-mi8wM6xm7rRBMYTCjHfM5}"

SCAN_RESULTS="$HOME/.trufflehog_results.jsonl"
: > "$SCAN_RESULTS"
mkdir -p "$HOME/.run_pids"
PIDFILE="$HOME/.run_pids/crypto_scanner.pid"

if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    echo "[*] Wallet scanner already running (PID $(cat "$PIDFILE"))"
    notify "Wallet scanner already running"
else
    rm -f "$PIDFILE"
    nohup python3 "$HOME/crypto_scanner.py" "$SCAN_RESULTS" >> "$HOME/crypto_scanner_scanner.log" 2>&1 &
    echo $! > "$PIDFILE"
    echo "[+] Wallet scanner started (PID $(cat "$PIDFILE"))"
    notify "Wallet scanner started"
    sleep 1
fi

echo ""
echo "Recent scanner output:"
tail -n 25 "$HOME/crypto_scanner_scanner.log" 2>/dev/null || echo "[no log yet]"
echo ""
echo "Log file: $HOME/crypto_scanner_scanner.log"
echo "Status:   $HOME/crypto_scanner_status.txt"
echo "Hits:     $HOME/high_confidence_hits.jsonl"
wait_key
EOF

# 3. StopAll
cat > "$SHORTCUT_DIR/StopAll" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
banner() {
    echo "========================================"
    echo "$1"
    echo "========================================"
    echo ""
}
wait_key() {
    echo ""
    read -n 1 -s -r -p "Tap any key to close..." || true
    echo ""
}
notify() {
    termux-toast "$1" 2>/dev/null || true
}

banner "StopAll - Stopping scanners"
notify "Stopping all scanners..."
bash "$HOME/stop_all.sh"
echo ""
echo "[+] All scanners stopped"
notify "All scanners stopped"
wait_key
EOF

# 4. ScannerStatus
cat > "$SHORTCUT_DIR/ScannerStatus" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
banner() {
    echo "========================================"
    echo "$1"
    echo "========================================"
    echo ""
}
wait_key() {
    echo ""
    read -n 1 -s -r -p "Tap any key to close..." || true
    echo ""
}
notify() {
    termux-toast "$1" 2>/dev/null || true
}

banner "Scanner Status"

STATUS_FILE="$HOME/crypto_scanner_status.txt"
PIDFILE="$HOME/.run_pids/crypto_scanner.pid"
MASS_PIDFILE="$HOME/.run_pids/mass_scan.pid"

if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
    echo "Crypto scanner: RUNNING (PID $(cat "$PIDFILE"))"
else
    echo "Crypto scanner: STOPPED"
fi

if [ -f "$MASS_PIDFILE" ] && kill -0 "$(cat "$MASS_PIDFILE")" 2>/dev/null; then
    echo "Mass scan:      RUNNING (PID $(cat "$MASS_PIDFILE"))"
else
    echo "Mass scan:      STOPPED"
fi

echo ""
if [ -f "$STATUS_FILE" ]; then
    STATUS="$(cat "$STATUS_FILE")"
    echo "Last status:"
    echo "$STATUS"
    notify "$STATUS"
else
    echo "[*] No status file yet"
    notify "No status yet"
fi

echo ""
echo "Recent log tail:"
tail -n 15 "$HOME/crypto_scanner_scanner.log" 2>/dev/null || echo "[no log yet]"
wait_key
EOF

# 5. WalletView (balance checker visual)
cat > "$SHORTCUT_DIR/WalletView" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
python3 "$HOME/wallet_view.py"
echo ""
read -n 1 -s -r -p "Tap any key to close..." || true
echo ""
EOF

# 6. PasteBox
cat > "$SHORTCUT_DIR/PasteBox" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Generated by install_home_shortcuts.sh

clear
banner() {
    echo "========================================"
    echo "$1"
    echo "========================================"
    echo ""
}
wait_key() {
    echo ""
    read -n 1 -s -r -p "Tap any key to close..." || true
    echo ""
}
notify() {
    termux-toast "$1" 2>/dev/null || true
}

banner "PasteBox - Processing input"
notify "Processing paste box..."
python3 "$HOME/paste_box.py"
notify "Paste box processed"

echo ""
echo "=== Summary ==="
printf "GitHub targets:  "; wc -l < "$HOME/paste.txt" 2>/dev/null || echo 0
printf "Crypto findings: "; wc -l < "$HOME/.trufflehog_results.jsonl" 2>/dev/null || echo 0
printf "RPC endpoints:   "; wc -l < "$HOME/rpc_endpoints.jsonl" 2>/dev/null || echo 0
printf "API keys:        "; wc -l < "$HOME/api_keys.jsonl" 2>/dev/null || echo 0

echo ""
echo "Next step: tap CryptoScanner (wallet scanner) to scan the findings."
wait_key
EOF

chmod +x "$SHORTCUT_DIR"/*

# Also create a "WalletScanner" alias shortcut (same as CryptoScanner)
cp -f "$SHORTCUT_DIR/CryptoScanner" "$SHORTCUT_DIR/WalletScanner"
chmod +x "$SHORTCUT_DIR/WalletScanner"

# Also install as dynamic shortcuts for Termux:Widget
DYNAMIC_DIR="$HOME_DIR/.termux/widget/dynamic_shortcuts"
mkdir -p "$DYNAMIC_DIR"
cp -f "$SHORTCUT_DIR"/* "$DYNAMIC_DIR/"
chmod +x "$DYNAMIC_DIR"/*

# Boot script
cat > "$BOOT_DIR/01_launch_crypto_scanner.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
sleep 10
termux-wake-lock 2>/dev/null || true
bash "$HOME/launch_all.sh" > "$HOME/termux_boot.log" 2>&1 &
EOF
chmod +x "$BOOT_DIR/01_launch_crypto_scanner.sh"

echo "[+] Shortcuts installed in $SHORTCUT_DIR"
echo "[+] Boot script installed in $BOOT_DIR"
echo ""
echo "To add icons to your home screen:"
echo "  1) Long-press empty home screen -> Widgets"
echo "  2) Find Termux:Widget"
echo "  3) Drag any shortcut (LaunchAll, CryptoScanner, StopAll, ScannerStatus) to home"
